server:
  port: 8761

eureka:
  instance:
    hostname: localhost  # The hostname where the Eureka server is running
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: HRM-SERVICE-REGISTRY